import mongoose from "mongoose";

const hotel_mealsModel= new mongoose.Schema({

    Hotel_Id : Number,
    Hotel_name : String,
    A_la_carte_dinner : Boolean,
    A_la_carte_lunch : Boolean,
    All_inclusive : Boolean,
    All_inclusive_with_alcoholic_drinks_own_brands : Boolean,
    All_inclusive_with_alcoholic_drinks_top_brands : Boolean,
    All_inclusive_with_non_alcoholic_drinks : Boolean,
    All_inclusive_without_drinks : Boolean,
    Breakfast : Boolean,
    Breakfast_a_la_carte : Boolean,
    Breakfast_and_dinner : Boolean,
    Breakfast_and_lunch : Boolean,
    Breakfast_buffet : Boolean,
    Breakfast_served_to_the_table : Boolean,
    Brunch : Boolean,
    Buffet_dinner : Boolean,
    Buffe_lunch : Boolean,
    Continental_breakfast : Boolean,
    Early_bird_breakfast : Boolean,
    Full_board : Boolean,
    Full_Board_with_drinks : Boolean,
    Full_board_with_non_alcoholic_drinks : Boolean,
    Full_board_without_drinks : Boolean,
    Gala_dinner : Boolean,
    Gluten_free_meals : Boolean,
    Half_Board : Boolean,
    Half_board_with_drinks : Boolean,
    Half_board_with_non_alcoholic_drinks : Boolean,
    Half_board_without_drinks : Boolean,
    Hot_breakfast : Boolean,
    Late_riser_breakfast : Boolean,
    No_alcohol_is_served : Boolean,
    Picnic : Boolean,
    Set_menu_dinner : Boolean,
    Set_menu_lunch : Boolean,
    Snaks : Boolean,
    special_dietary_options : Boolean,
    Vegetarian_meal : Boolean,
});

export const Hotel_Meals = mongoose.models.hotel_meals || mongoose.model("hotel_meals",hotel_mealsModel)