import mongoose from "mongoose";

const hotel_health_and_safety_covidModel= new mongoose.Schema({
    Hotel_Id : Number,
    Hotel_name : String,
    ABBA_safety_plan : Boolean,
    Accor_ALLSAFE : Boolean,
    AM_Clean_Complete_Verification : Boolean,
    Argentina_Protocol_COVID_19_para_Alojamientos_turísticos : Boolean,
    Ascott_Ascott_Cares : Boolean,
    Australia_We_are_Covid_Safe : Boolean,
    Austria_COVID_19_Lockerungsverordnung : Boolean,
    B_and_B_Ireland_Care_Policy : Boolean,
    Barcelo_We_care_about_you : Boolean,
    Bayan_Tree_SafeSanctuary_Programme : Boolean,
    Best_Hotels_Blue_Health : Boolean,
    Best_Western_We_Care_Clean : Boolean,
    Blue_Diamond_Resorts_Enhanced_Health_Safety_and_Cleanliness_Protocols : Boolean,
    Blue_Sea_Safety_and_Hygiene_Measures : Boolean,
    BlueBay_Clean_and_Care : Boolean,
    Brazil_Turismo_Responsavel_limpo_e_seguro : Boolean,
    Bulgaria_Protocol_for_operation_of_accommodation_and_catering : Boolean,
    Caesars_Health_and_Safety_protocols : Boolean,
    Catalonia_Global_Commitment_to_Safeguard_our_guests : Boolean,
    Centara_Complete_Care : Boolean,
    Chile_Protocolo_general_de_Manejo_y_Prevencion_ante_COVID_19_en_el_sector_Turismo_y_Alojamiento : Boolean,
    Choice_Hotels_Commitment_to_Clean : Boolean,
    Colombia_Check_in_certificado_COVID_19_bioseguro : Boolean,
    Costa_Rica_ICT_P_001_Protocolo_para_actividades_de_hospedaje_Sector_Turismo : Boolean,
    Croatia_Recommendations_for_hotels_and_renters_during_the_COVID_19 : Boolean,
    Crystal_Hygienic_Concept : Boolean,
    Cyprus_Precautionary_measures_against_the_spread_of_COVID_19_for_Hotel_and_Tourist_Accomm_Managers : Boolean,
    Czeck_Republic_Stay_Safe : Boolean,
    Dedeman_Stay_Safe : Boolean,
    Diamond_Standard_of_Clean : Boolean,
    Disneyland_Paris_Enhanced_health_and_safety_measures : Boolean,
    Dominican_Republic_Protocolo_Sectorial_Turismo : Boolean,
    Duba_Dubai_Assured : Boolean,
    Ecuador_Protocolo_General_para_establecimientos_de_alojamiento_turístico : Boolean,
    Egypt_Life_Prosperity_Health : Boolean,
    Eurostars_Clean_and_Safe : Boolean,
    Fiji_CovidSafeGuidelineforTourismIndustry : Boolean,
    Four_Seasons_Lead_With_Care : Boolean,
    France_Protocole_de_deconfinement_commun_a_toute_la_profession_HCR : Boolean,
    Gargallo_Feel_Safe : Boolean,
    GHG_COVID_19_Prevention : Boolean,
    Globales_Protocol_COVID_19 : Boolean,
    Greece_Health_First : Boolean,
    H10_Safety_Program_by_H10 : Boolean,
    Highgate_Be_Well_Stay_Well : Boolean,
    Hilton_CleanStay : Boolean,
    Hotelbeds_Supplier_Guidelines : Boolean,
    Hungary_Information_for_Operators_of_Commercial_Accommodation : Boolean,
    Hyatt_GBAC_STAR_Global_Care_and_Cleanliness_Commitment : Boolean,
    Iberostar_How_we_care : Boolean,
    IHG_Clean_Promise : Boolean,
    Ireland_Guidelines_for_re_opening_Hotelsand_Guesthouses : Boolean,
    Italy_Protocollo_nazionale_Accoglienza_Sicura : Boolean,
    Jamaica_Jamaica_Tourism_Covid_19_Protocols : Boolean,
    Jurys_Inn_Stay_Safe_Stay_Happy : Boolean,
    Kempinski_White_Glove : Boolean,
    Leonardo_Hotel_Stay_Guidelines : Boolean,
    Logis_Commitments_charter_for_a_Safer_Stay : Boolean,
    Louvre_Charte_of_Commitment : Boolean,
    Luxembourg_HORESCA_Safe_to_Serve : Boolean,
});

export const Hotel_Health_And_Safety_Covid = mongoose.models.hotel_health_and_safety_covid || mongoose.model("hotel_health_and_safety_covid",hotel_health_and_safety_covidModel)