import mongoose from "mongoose";

const hotel_facilitiesModel= new mongoose.Schema({

    Hotel_Id : Number,
    Hotel_name : String,
    reception_24_hour : Boolean,
    security_24_hour : Boolean,
    Air_conditioning_in_public_areas : Boolean,
    Airport_Shuttle : Boolean,
    Babysitting_service : Boolean,
    BBQ_facilities : Boolean,
    Belboy_Service : Boolean,
    Bicycle_Hire_Service : Boolean,
    Bicycle_Storage : Boolean,
    Bikes_available : Boolean,
    Car_hire : Boolean,
    Car_park : Boolean,
    Cloakroom : Boolean,
    Clothes_dryer : Boolean,
    Concierge : Boolean,
    Currency_Exchange_Facilities : Boolean,
    Day_care_center : Boolean,
    Dining_area : Boolean,
    Electric_Kettle : Boolean,
    Electric_vehicle_charging_station : Boolean,
    Fireplace : Boolean,
    Grage : Boolean,
    Garden : Boolean,
    Golf_desk : Boolean,
    Grill_BBQ : Boolean,
    Gym : Boolean,
    Hotel_safe : Boolean,
    Hotels_own_bike_shop_workshop : Boolean,
    Large_pets_allowed_over_5kg : Boolean,
    Late_Check_Out : Boolean,
    Launderette : Boolean,
    Laundry_service : Boolean,
    Library : Boolean,
    Lift_access : Boolean,
    Local_and_international_calls : Boolean,
    Luggage_room : Boolean,
    Medical_service : Boolean,
    Mobile_phone_coverage : Boolean,
    Multilingual_staff : Boolean,
    Newspaper_stand : Boolean,
    Newspapers : Boolean,
    Oven : Boolean,
    Partners_bike_shop_workshop : Boolean,
    Private_beach_area : Boolean,
    Private_Pool : Boolean,
    Room_service : Boolean,
    Secure_parking : Boolean,
    Shop : Boolean,
    Ski_storage : Boolean,
    ski_to_door_access : Boolean,
    Small_pets_allowed_under_5kg : Boolean,
    smoke_detector : Boolean,
    sun_terrace : Boolean,
    Supermarket : Boolean,
    Terrace : Boolean,
    Toaster : Boolean,
    Towels_and_bed_linen : Boolean,
    Transfer_service : Boolean,
    Vaiet_parking : Boolean,
    Wheelchair_accessible : Boolean,
    wi_fi : Boolean,
    wired_internet : Boolean,
    smoke_room : Boolean,
    couple_policy : Boolean,
    pay_at_hotel : Boolean,
    local_id_accepted : Boolean

});

export const Hotel_Facilities = mongoose.models.hotel_facilities || mongoose.model("hotel_facilities",hotel_facilitiesModel)